### ISSUE TITLE
01_deploy.sh script error

### ISSUE THREAD

**Issue by andyoulovexy** [V1D1AN/S1EM#109]
I had modified 01_deploy.sh,now it's work
[01_deploy.txt](https://github.com/V1D1AN/S1EM/files/12117515/01_deploy.txt)

**Comment by V1D1AN** [comment]
Hi @andyoulovexy,

The script works for docker compose v2.
Now the docker compose start with "docker compose" and not "docker-compose"

Thanks for your help. I will be more precise on the documentation of installation.
