### ISSUE TITLE
Upgrade to Elastic 7.14.0

### ISSUE THREAD

**Issue by frack113** [V1D1AN/S1EM#22]
Hi,
[Elastic 7.14](https://www.elastic.co/guide/en/kibana/7.x/release-notes-7.14.0.html) is available.
Many change to [security](https://www.elastic.co/guide/en/security/7.x/release-notes.html) :fireworks:

So can you add to the short roadmap .
Thanks

**Comment by V1D1AN** [comment]
I will update to ELK 7.14.0

**Comment by StevenD33** [comment]
Issue can be closed this commit upgrade ELK to 7.14.1 [https://github.com/V1D1AN/S1EM/commit/1dcae1fea133f51bbca01ec1f9f123272072b9a7](https://github.com/V1D1AN/S1EM/commit/1dcae1fea133f51bbca01ec1f9f123272072b9a7)
