### ISSUE TITLE
Kibana Is Not Online, OpenCTI is 404

### ISSUE THREAD

**Issue by btxcode** [V1D1AN/S1EM#25]
Hello,

When im deploy with 01_deploy.sh
stuck in messages " Wait to kibana online"
and when i run the web opencti is 404

**Comment by V1D1AN** [comment]
Hi,

In your "/etc/sysctl.conf" have you got the line "vm.max_map_count=262144" ?

**Comment by cobrahackingacademy** [comment]
Hi,
I'm having the same issue and I added that line to "/etc/sysctl.conf"
