### ISSUE TITLE
Error on Heimdall when running deploy shell script

### ISSUE THREAD

**Issue by salimadnan** [V1D1AN/S1EM#33]
Error: near line 4: UNIQUE constraint failed: items.id
Error: near line 5: UNIQUE constraint failed: items.id
Error: near line 6: UNIQUE constraint failed: items.id
Error: near line 7: UNIQUE constraint failed: items.id
Error: near line 8: UNIQUE constraint failed: items.id
Error: near line 9: UNIQUE constraint failed: items.id
Error: near line 10: UNIQUE constraint failed: items.id
Error: near line 11: UNIQUE constraint failed: items.id
Error: near line 12: UNIQUE constraint failed: items.id
Error: near line 13: UNIQUE constraint failed: items.id
Error: near line 14: UNIQUE constraint failed: items.id
Error: near line 15: UNIQUE constraint failed: items.id

**Comment by V1D1AN** [comment]
Hi,

Have you do the install under user root ?
Can you send me log of the heimdall docker ?

```
docker logs heimdall
```

**Comment by StevenD33** [comment]
no reply, feel free to reopen with further infos for debug
