### ISSUE TITLE
Waiting for Cortex to come online.

### ISSUE THREAD

**Issue by salim391** [V1D1AN/S1EM#39]
{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}

**Comment by salim391** [comment]
{"type":"InternalError","message":"Unknown error: ElasticError(java.lang.RuntimeException,Error with index exists request (http code 401,None,None,None,List(),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_doc/Aspire+Tech?routing=Aspire+Tech&refresh=wait_for&op_type=create],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_doc/Aspire+Tech?routing=Aspire+Tech&refresh=wait_for&op_type=create],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}{"type":"InternalError","message":"Unknown error: ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,List(ElasticError(security_exception,unable to authenticate user [elastic] for REST request [/cortex_6/_search],None,None,None,null,None,None,None,List())),None,None,None,List())"}

**Comment by V1D1AN** [comment]
> {"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}

Hi,

Cortex use elasticsearch.  The elasticsearch was start ? 
Can you send me log of the es01 docker ?

```
docker logs es01
```
