### ISSUE TITLE
S1EM installation suported linux distros

### ISSUE THREAD

**Issue by NPascar** [V1D1AN/S1EM#43]
Hi Vidian.. hope all is well. What are the supported linux distros for the installation . I was trying with ubuntu 20.04 but im getting errors when i run the setup script. Error says docker command not found.

**Comment by NPascar** [comment]
Im getting this error when i try to install


########################################
#### CONFIGURING MONITORING INTERFACE ####
##########################################
 
 
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:03:fe:16 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.101/24 brd 192.168.2.255 scope global eth0
--
3: eth1: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:03:fe:19 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::215:5dff:fe03:fe19/64 scope link
 
 
Enter the monitoring interface (ex:ens32):eth1
cp: cannot create regular file '/usr/lib/systemd/system/S1EM-promiscuous.service': No such file or directory
chmod: cannot access '/usr/lib/systemd/system/S1EM-promiscuous.service': No such file or directory
sed: can't read /usr/lib/systemd/system/S1EM-promiscuous.service: No such file or directory
Failed to enable unit: Unit file S1EM-promiscuous.service does not exist.
Failed to start S1EM-promiscuous.service: Unit S1EM-promiscuous.service not found.
 
 
##########################################
######### GENERATE CERTIFICATE ###########
##########################################
 
 
01_deploy.sh: line 98: docker-compose: command not found
 
 
##########################################
########## DOCKER DOWNLOADING ############
##########################################
 
 
01_deploy.sh: line 106: docker-compose: command not found
 
 
##########################################
########## STARTING TRAEFIK ##############
##########################################
 
 
01_deploy.sh: line 114: docker-compose: command not found
 
 
##########################################
######### CONFIGURING TRAEFIK ############
##########################################
 
 
Error: No such container: traefik
Error: No such container: traefik
01_deploy.sh: line 125: docker-compose: command not found
 
 
##########################################
########### STARTING HEIMDALL ############
##########################################
 
01_deploy.sh: line 132: docker-compose: command not found
Error: No such container: heimdall
Error: No such container: heimdall
Error: No such container: heimdall
 
 
##########################################
##### STARTING ELASTICSEARCH/KIBANA ######
##########################################
 
 
01_deploy.sh: line 143: docker-compose: command not found
Error: No such container: es01
Waiting for Elasticsearch to come online.
Error: No such container: es01
Waiting for Elasticsearch to come online.
Error: No such container: es01
Waiting for Elasticsearch to come online.

**Comment by StevenD33** [comment]
> Im getting this error when i try to install
> 
> ########################################
> 
> #### CONFIGURING MONITORING INTERFACE
> ## ##########################################
>  
>  
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 00:15:5d:03:fe:16 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.2.101/24 brd 192.168.2.255 scope global eth0
> 3: eth1: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000     link/ether 00:15:5d:03:fe:19 brd ff:ff:ff:ff:ff:ff     inet6 fe80::215:5dff:fe03:fe19/64 scope link     Enter the monitoring interface (ex:ens32):eth1 cp: cannot create regular file '/usr/lib/systemd/system/S1EM-promiscuous.service': No such file or directory chmod: cannot access '/usr/lib/systemd/system/S1EM-promiscuous.service': No such file or directory sed: can't read /usr/lib/systemd/system/S1EM-promiscuous.service: No such file or directory Failed to enable unit: Unit file S1EM-promiscuous.service does not exist. Failed to start S1EM-promiscuous.service: Unit S1EM-promiscuous.service not found.     ########################################## ######### GENERATE CERTIFICATE ########### ##########################################     01_deploy.sh: line 98: docker-compose: command not found     ########################################## ########## DOCKER DOWNLOADING ############ ##########################################     01_deploy.sh: line 106: docker-compose: command not found     ########################################## ########## STARTING TRAEFIK ############## ##########################################     01_deploy.sh: line 114: docker-compose: command not found     ########################################## ######### CONFIGURING TRAEFIK ############ ##########################################     Error: No such container: traefik Error: No such container: traefik 01_deploy.sh: line 125: docker-compose: command not found     ########################################## ########### STARTING HEIMDALL ############ ##########################################   01_deploy.sh: line 132: docker-compose: command not found Error: No such container: heimdall Error: No such container: heimdall Error: No such container: heimdall     ##########################################
> 
> ##### STARTING ELASTICSEARCH/KIBANA
> ##########################################     01_deploy.sh: line 143: docker-compose: command not found Error: No such container: es01 Waiting for Elasticsearch to come online. Error: No such container: es01 Waiting for Elasticsearch to come online. Error: No such container: es01 Waiting for Elasticsearch to come online.

you need to have docker and docker-compose for the setup and to launch the script as root.

**Comment by NPascar** [comment]
Okay.. thanx a lot.. i will try that

**Comment by NPascar** [comment]
Thanx.. it installed succefully after installing the docker components.. 👍

**Comment by NPascar** [comment]
Hi im getting error pulling the following packeges :

ERROR: for opencti  Get "https://registry-1.docker.io/v2/opencti/platform/manifests/sha256:227f1caea0945b1e6b4ec3ea0ecee5a829d61772d2b6a4c55a45ced712a3d16e": net/http: TLS handshake timeout
ERROR: for misp  error pulling image configuration: Get "https://registry-1.docker.io/v2/coolacid/misp-docker/blobs/sha256:8a75067113662df6e238fc78ea3f5829091b39769f0f973fc729d2bb35e993c0": net/http: TLS handshake timeout
ERROR: for connector-history  Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout
ERROR: for stoq  Head "https://registry-1.docker.io/v2/v1d1an/stoq/manifests/3.0.5": Get "https://auth.docker.io/token?scope=repository%3Av1d1an%2Fstoq%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
ERROR: for postgres  Get "https://registry-1.docker.io/v2/library/postgres/manifests/sha256:92876ceccfd7bec0d5c4f3c0ab7e13e7e2bb7368e7430f8b8ba52548f1e47abf": net/http: TLS handshake timeout
ERROR: for cyberchef  Head "https://registry-1.docker.io/v2/mpepping/cyberchef/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Ampepping%2Fcyberchef%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
ERROR: for karton-yaramatcher  error pulling image configuration: Get "https://registry-1.docker.io/v2/certpl/karton-yaramatcher/blobs/sha256:cf79025a1bb4672ff73b0cbc34533a0c4f576aec9ace5ba0d90f72ade77a20b7": net/http: TLS handshake timeout
ERROR: for connector-alienvault  error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/56/56b717f5d0cf04f91e3b9936b615efbe0cf5d199f98c7402f83501588b685921/data?verify=1642420988-nCAdZ6ekRUhCdLRb7p4pUe5QeW4%3D": net/http: TLS handshake timeout
ERROR: for thehive  error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/4f/4f22b0c1790e7e652d48cdbfb91970b3cc09557d932dd9a30ca37ec99383b888/data?verify=1642421131-g8KgpvpwXSAbW34XQAmoIwwzoMY%3D": net/http: TLS handshake timeout
ERROR: for karton-mwdb-reporter  error pulling image configuration: Get "https://registry-1.docker.io/v2/certpl/karton-mwdb-reporter/blobs/sha256:5890e53d00e6fe6a751550b0c11994b7fcbb886abdacb476163b852f03737ee0": net/http: TLS handshake timeout
ERROR: for worker  Get "https://registry-1.docker.io/v2/opencti/worker/manifests/sha256:2ae1a11ec6d8035e7211467b9216277d994a65d6c5d691a4520c33f0e0e5bd69": net/http: TLS handshake timeout
ERROR: for zeek  error pulling image configuration: Get "https://registry-1.docker.io/v2/blacktop/zeek/blobs/sha256:410cf785c68795879a4bf737d578ce41bef3aea0f9e94a8008fe26a7b2c74b68": net/http: TLS handshake timeout
ERROR: error pulling image configuration: Get "https://registry-1.docker.io/v2/blacktop/zeek/blobs/sha256:410cf785c68795879a4bf737d578ce41bef3aea0f9e94a8008fe26a7b2c74b68": net/http: TLS handshake timeout

**Comment by NPascar** [comment]
Hi im getting error pulling the following packeges :

ERROR: for opencti  Get "https://registry-1.docker.io/v2/opencti/platform/manifests/sha256:227f1caea0945b1e6b4ec3ea0ecee5a829d61772d2b6a4c55a45ced712a3d16e": net/http: TLS handshake timeout
ERROR: for misp  error pulling image configuration: Get "https://registry-1.docker.io/v2/coolacid/misp-docker/blobs/sha256:8a75067113662df6e238fc78ea3f5829091b39769f0f973fc729d2bb35e993c0": net/http: TLS handshake timeout
ERROR: for connector-history  Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout
ERROR: for stoq  Head "https://registry-1.docker.io/v2/v1d1an/stoq/manifests/3.0.5": Get "https://auth.docker.io/token?scope=repository%3Av1d1an%2Fstoq%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
ERROR: for postgres  Get "https://registry-1.docker.io/v2/library/postgres/manifests/sha256:92876ceccfd7bec0d5c4f3c0ab7e13e7e2bb7368e7430f8b8ba52548f1e47abf": net/http: TLS handshake timeout
ERROR: for cyberchef  Head "https://registry-1.docker.io/v2/mpepping/cyberchef/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Ampepping%2Fcyberchef%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
ERROR: for karton-yaramatcher  error pulling image configuration: Get "https://registry-1.docker.io/v2/certpl/karton-yaramatcher/blobs/sha256:cf79025a1bb4672ff73b0cbc34533a0c4f576aec9ace5ba0d90f72ade77a20b7": net/http: TLS handshake timeout
ERROR: for connector-alienvault  error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/56/56b717f5d0cf04f91e3b9936b615efbe0cf5d199f98c7402f83501588b685921/data?verify=1642420988-nCAdZ6ekRUhCdLRb7p4pUe5QeW4%3D": net/http: TLS handshake timeout
ERROR: for thehive  error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/4f/4f22b0c1790e7e652d48cdbfb91970b3cc09557d932dd9a30ca37ec99383b888/data?verify=1642421131-g8KgpvpwXSAbW34XQAmoIwwzoMY%3D": net/http: TLS handshake timeout
ERROR: for karton-mwdb-reporter  error pulling image configuration: Get "https://registry-1.docker.io/v2/certpl/karton-mwdb-reporter/blobs/sha256:5890e53d00e6fe6a751550b0c11994b7fcbb886abdacb476163b852f03737ee0": net/http: TLS handshake timeout
ERROR: for worker  Get "https://registry-1.docker.io/v2/opencti/worker/manifests/sha256:2ae1a11ec6d8035e7211467b9216277d994a65d6c5d691a4520c33f0e0e5bd69": net/http: TLS handshake timeout
ERROR: for zeek  error pulling image configuration: Get "https://registry-1.docker.io/v2/blacktop/zeek/blobs/sha256:410cf785c68795879a4bf737d578ce41bef3aea0f9e94a8008fe26a7b2c74b68": net/http: TLS handshake timeout
ERROR: error pulling image configuration: Get "https://registry-1.docker.io/v2/blacktop/zeek/blobs/sha256:410cf785c68795879a4bf737d578ce41bef3aea0f9e94a8008fe26a7b2c74b68": net/http: TLS handshake timeout


Please assist me here..

**Comment by V1D1AN** [comment]
You have problem with your connection Internet. Normally, the docker-compose download image from docker hub.
Can you ping google ?? You have access to internet ?

**Comment by NPascar** [comment]
The internet seems fine.. maybe i have some DNS issues.. i will try to trouble shoot. Im trying to install on ubuntu 20.04 LTS is that fine? Or should i use 18.04?!

**Comment by StevenD33** [comment]
i tested it on ubuntu 20.04 it work fine with me, it should work with you without the dns problem you have

**Comment by NPascar** [comment]
Thanx.. i installed on 20.04 and seems to be working. All seems to be fine at first until in get that: Waiting for Elasticsearch to come online message at the end.. its not advancing any further from that message.

##########################################
########## DOCKER DOWNLOADING ############
##########################################
 
 
Pulling traefik                    ... done
Pulling es01                       ... done
Pulling es02                       ... done
Pulling es03                       ... done
Pulling logstash                   ... done
Pulling kibana                     ... done
Pulling auditbeat                  ... done
Pulling heartbeat                  ... done
Pulling metricbeat                 ... done
Pulling filebeat                   ... done
Pulling syslog-ng                  ... done
Pulling suricata                   ... done
Pulling stoq                       ... done
Pulling zeek                       ... done
Pulling tcpreplay                  ... done
Pulling file-upload                ... done
Pulling cortex                     ... done
Pulling cassandra                  ... done
Pulling thehive                    ... done
Pulling elastalert                 ... done
Pulling redis                      ... done
Pulling db                         ... done
Pulling misp                       ... done
Pulling misp-modules               ... done
Pulling postgres                   ... done
Pulling minio                      ... done
Pulling karton-mwdb-reporter       ... done
Pulling karton-archive-extractor   ... done
Pulling karton-asciimagic          ... done
Pulling karton-yaramatcher         ... done
Pulling karton-classifier          ... done
Pulling karton-system              ... done
Pulling mwdb                       ... done
Pulling mwdb-web                   ... done
Pulling rabbitmq                   ... done
Pulling worker                     ... done
Pulling connector-history          ... done
Pulling connector-export-file-stix ... done
Pulling connector-export-file-csv  ... done
Pulling connector-import-file-stix ... done
Pulling connector-import-document  ... done
Pulling connector-misp             ... done
Pulling connector-mitre            ... done
Pulling connector-cve              ... done
Pulling connector-alienvault       ... done
Pulling connector-amitt            ... done
Pulling connector-opencti          ... done
Pulling opencti                    ... done
Pulling cyberchef                  ... done
Pulling heimdall                   ... done
Pulling arkime                     ... done
Pulling import                     ... done
Pulling clamav                     ... done
Pulling watchtower                 ... done
 
 
##########################################
########## STARTING TRAEFIK ##############
##########################################
 
 
traefik is up-to-date
 
 
##########################################
######### CONFIGURING TRAEFIK ############
##########################################
 
 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
OK: 11 MiB in 21 packages
sed: -e expression #1, char 76: unterminated `s' command
Restarting traefik ... done
 
 
##########################################
########### STARTING HEIMDALL ############
##########################################
 
heimdall is up-to-date
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.9-33-g3928da42a4 [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.9-30-g69c35febbc [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12755 distinct packages available
OK: 67 MiB in 80 packages
Error: near line 4: UNIQUE constraint failed: items.id
Error: near line 5: UNIQUE constraint failed: items.id
Error: near line 6: UNIQUE constraint failed: items.id
Error: near line 7: UNIQUE constraint failed: items.id
Error: near line 8: UNIQUE constraint failed: items.id
Error: near line 9: UNIQUE constraint failed: items.id
Error: near line 10: UNIQUE constraint failed: items.id
Error: near line 11: UNIQUE constraint failed: items.id
Error: near line 12: UNIQUE constraint failed: items.id
Error: near line 13: UNIQUE constraint failed: items.id
Error: near line 14: UNIQUE constraint failed: items.id
Error: near line 15: UNIQUE constraint failed: items.id
 
 
##########################################
##### STARTING ELASTICSEARCH/KIBANA ######
##########################################
 
 
Recreating es02 ...
Recreating es02 ... done
Recreating es03 ... done
kibana is up-to-date
Waiting for Elasticsearch to come online.
Waiting for Elasticsearch to come online.
Waiting for Elasticsearch to come online.
Waiting for Elasticsearch to come online.
Waiting for Elasticsearch to come online.
Waiting for Elasticsearch to come online.

**Comment by NPascar** [comment]
Hi Guys.. im still failing to install S1EM.. i want to make this part of my school research project. 
Is there perhaps a pre configured image that i can download ?

**Comment by StevenD33** [comment]
this error it's not an error the script is just telling you to wait for elasticsearch, let it work and wait at least 10-15 minutes and after that s1em should be functionnal

**Comment by NPascar** [comment]
Okay.. i will try again

**Comment by NPascar** [comment]
Hi guys.. i tried to install again.. but still no success.. can you perhaps share a step by step installation guide on how to install S1EM.. maybe there is something im missing, perhaps some post installation settings for docker and docker compose setting before the S1EM installation.

**Comment by StevenD33** [comment]
i'll share a OVA of an S1EM install i have some time this week.

did you apply the virtual memory settings in your configuraiton ? 
https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

**Comment by NPascar** [comment]
Hi.. thank you for reply.. that would awsome to share an ova.. yes i did virtual memory settings on the server. Thats the first thing i did before install anything.. can you perhaps share also share a step by step manual, which include the docker and compose installation part.. i keep thinking that maybe theres something im missing at the begining.

**Comment by V1D1AN** [comment]
You have a discord channel for talking about S1EM

**Comment by NPascar** [comment]
Hi.. No i dont have have any channel, i want to venture into the cyber security realm, blue team staff to be more precise. I want to finish my honors degree in cyber security and i want to make this tool as part of my facts finding resources. Its would really help me.

**Comment by V1D1AN** [comment]
https://discord.gg/6Q8aQGYE

**Comment by NPascar** [comment]
Hi.. i just joined discord.. can you paste your invitation link again, it seems it has expired or something.

**Comment by V1D1AN** [comment]
https://discord.gg/uPBguSB2

**Comment by StevenD33** [comment]
Im closing this issue feel free to reopen one or contact us on discord if you have another problem with the installation
