### ISSUE TITLE
What are the advantages compared to security onion?

### ISSUE THREAD

**Issue by D0n9** [V1D1AN/S1EM#53]
I am evaluating SELKS and security onion and S1EM and am confused as to which one to choose and what are the similarities and differences between them.

**Comment by V1D1AN** [comment]
Hello D0n9

This is a very good question and unfortunately I couldn't give the best answer.
I have used SELKS but the solution is exclusively based on Suricata.
The S1EM solution is closer to SecurityOnion in idea.
Then, S1EM is the fruit of my imagination when I used solutions like RockNSM, SecurityOnion, Ossim.
I wanted a solution that could be deployed quickly (thanks to docker) and that would answer my need to have a solution that interconnects.

Better than SecurityOnion, I don't know, just different.
