### ISSUE TITLE
yaml: line 1460: did not find expected key

### ISSUE THREAD

**Issue by Akityo** [V1D1AN/S1EM#55]
## Description

Enter the monitoring interface (ex:ens32):ens37
Failed to start S1EM-promiscuous.service: Unit is not loaded properly: Invalid argument.
See system logs and 'systemctl status S1EM-promiscuous.service' for details.

##########################################
##########################################

yaml: line 1460: did not find expected key

##########################################
##########################################

yaml: line 1460: did not find expected key

##########################################
##########################################

yaml: line 1460: did not find expected key

##########################################
##########################################

yaml: line 1460: did not find expected key

##########################################
##########################################

yaml: line 1460: did not find expected key
Error: No such container: es01
Waiting for Elasticsearch to come online.

## Environment

Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.9.2009 (Core)

[root@localhost S1EM]# docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:48:24 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

[root@localhost S1EM]# docker-compose version
Docker Compose version v2.4.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Screenshots (optional)

**Comment by V1D1AN** [comment]
Hi,

I will search for this problem

**Comment by V1D1AN** [comment]
Can you re test please..
I have correct a bug in the docker-compose.

**Comment by Akityo** [comment]
@V1D1AN  it work fine , thanks for your great job, this is a great project .
