### ISSUE TITLE
Arkime, Spiderfoot, Cyberchef, CodiMD, Upload do not work

### ISSUE THREAD

**Issue by ap6xd** [V1D1AN/S1EM#56]
Hi,

I followed all the steps and looked at all the logs. However, these services have not risen/are not accessible. Would you help me?

Taking advantage, I would like to thank you for the excellent work. It's amazing.

**Comment by V1D1AN** [comment]
Hi,

I have change some things.. Can you re-test a installation please ??

**Comment by ap6xd** [comment]
Hi,

Thx, works fine! 

Sorry, I just forgot to mention that MWDB doesn't open either.

Taking advantage... I would like to contribute to the project, as it helped me a lot in my job. It's possible to transfer some amount via paypal or crypto?

**Comment by ap6xd** [comment]
The log file of mwdb brings "psql: error: connection to server at "postgres" (172.28.0.12), port 5432 failed: FATAL:  password authentication failed for user "mwdb"
Waiting for postgres" but the password is correct. 

i checked in databases.sh file from postgres folder and also postgres-vars.env from mwdb folder. I tried to run the databases manually but it returns "./databases.sh: line 4: psql: command not found". Would it be necessary to add postgree to the PATH?

**Comment by ap6xd** [comment]
I resolved by re-deploying... I imagine he was using the old volume. After running "docker volume rm $(docker volume ls -q)" the problem was solved. Now doesn't open at browser, but running "curl localhost:8080 apparently it's ok.

Thx bro! Don't forget to send me how to donate!

**Comment by V1D1AN** [comment]
Thanks you for your feedback.

Tell me if you have idea.

I added a paypal button even if the project is not made to have money
