### ISSUE TITLE
ERROR: The Compose file

### ISSUE THREAD

**Issue by kernelr00ter** [V1D1AN/S1EM#57]
##########################################
##########################################

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.misp.hostname contains an invalid type, it should be a string

##########################################
##########################################

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.misp.hostname contains an invalid type, it should be a string

##########################################
##########################################

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.misp.hostname contains an invalid type, it should be a string

##########################################
##########################################

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.misp.hostname contains an invalid type, it should be a string

##########################################
##########################################

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.misp.hostname contains an invalid type, it should be a string
Error: No such container: es01
Waiting for Elasticsearch to come online.

**Comment by V1D1AN** [comment]
Hi,

I just tested with a domain name and it works
You must enter "toto.google.com" for example

**Comment by kernelr00ter** [comment]
In which file do you need to replace the domain name?
