### ISSUE TITLE
Add feature SSO

### ISSUE THREAD

**Issue by frack113** [V1D1AN/S1EM#7]
Hello,
Is it possible to add a SSO for all services with a AD or a LDAP ?
So the SOC man have just to logging to the front URL once.
The Best will be that all the internal password are in a vault only know by the vault and change every x day.

Thanks

**Comment by StevenD33** [comment]
I agree, SIEMonster has a feature like that

**Comment by frack113** [comment]
for Web login and ssh example : https://www.hashicorp.com/products/vault

**Comment by V1D1AN** [comment]
I will try to integrate vault for testing is good , Do it is best
