### ISSUE TITLE
Problem elastic nodes up

### ISSUE THREAD

**Issue by wallacepalace** [V1D1AN/S1EM#71]
Hey there, how are u?

I was doing some tests with your compose and I had the following problem... I ran the shellscript step by step, however, the elastic nodes do not go up because of this message, even though I configured the environment variables file correctly, it could help in that case, please?

Thanks!!

```
{"type": "server", "timestamp": "2022-10-26T06:11:05,075Z", "level": "INFO", "component": "o.e.x.s.a.RealmsAuthenticator", "cluster.name": "s1em", "node.name": "es01", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "W4fS5cU8Sdyp671yy0hVrg", "node.id": "YRM3VLPLQ4iEmw3wSyDZLA"  }
{"type": "server", "timestamp": "2022-10-26T06:11:07,572Z", "level": "INFO", "component": "o.e.x.s.a.RealmsAuthenticator", "cluster.name": "s1em", "node.name": "es01", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "W4fS5cU8Sdyp671yy0hVrg", "node.id": "YRM3VLPLQ4iEmw3wSyDZLA"  }
```

**Comment by V1D1AN** [comment]
Hi, 
When you do your test, do you suppress the folder S1EM and prune the volume of data01 data02 data03

**Comment by wallacepalace** [comment]
Hi, v1d1an, alright?

So I've already tested it a few times, including running "docker volume prune" every time :(

**Comment by V1D1AN** [comment]
Hi @wallacepalace 

Can you do a test for me please.
Check the ELASTIC_PASSWORD in your .env and on the file "TheHive/application.conf"
Can you tell me if the password for elastic is the same please.

**Comment by wallacepalace** [comment]
The passwords are different! Could this be the problem? I'll test it now.

**Comment by V1D1AN** [comment]
When , you have reinstalled , you must delete all the folder and all volume.
In the Next version ( thanks to "mcdave2k1" ) , there are scripts for cleaning the solution S1EM.

**Comment by V1D1AN** [comment]
Test the new version @wallacepalace
