### ISSUE TITLE
Can you commit a agent guide?

### ISSUE THREAD

**Issue by andyoulovexy** [V1D1AN/S1EM#74]
Can you commit a agent guide?How to install agent?how to configure it?thanks

**Comment by V1D1AN** [comment]
You can go on this github "https://github.com/m0ns7er/ElasticXDR"
The ElasticXDR from watsoninfosec is closed

**Comment by andyoulovexy** [comment]
> You can go on this github "https://github.com/m0ns7er/ElasticXDR" The ElasticXDR from watsoninfosec is closed

Got it,thanks
