### ISSUE TITLE
Upgrading .env when modif in env.sample

### ISSUE THREAD

**Issue by StevenD33** [V1D1AN/S1EM#9]
Hello

when i upgrade my S1EM version it does not upgrade my .env i had an error in my upgrade like 

```
ELASTIC_VERSION variable is not SET
```

maybe it should be said before upgrading to do a merge of the actual .env with the env.sample or do it automatically with the bash script.

**Comment by V1D1AN** [comment]
The elastic version variable is no longer in the env.sample file
