### ISSUE TITLE
Can't install S1EM

### ISSUE THREAD

**Issue by usenkov999** [V1D1AN/S1EM#96]
Hello!
Can't install S1EM
Ubuntu Server 20
latest docker & docker-compose

Starting of installation

##########################################
##########################################

/usr/local/bin/docker-compose: line 1: Not: command not found

##########################################
##########################################

/usr/local/bin/docker-compose: line 1: Not: command not found

##########################################
##########################################

/usr/local/bin/docker-compose: line 1: Not: command not found

##########################################
##########################################

/usr/local/bin/docker-compose: line 1: Not: command not found

##########################################
##########################################

/usr/local/bin/docker-compose: line 1: Not: command not found
Error response from daemon: No such container: es01
Waiting for Elasticsearch to come online.
^C

**Comment by V1D1AN** [comment]
for your installation,do this:
ln -s /usr/local/bin/docker-compose your_docker_compose
restart the installation
